services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.3  # 指定稳定版本
    container_name: qbittorrent
    user: "${PUID}:${PGID}"  # 显式声明用户
    environment:
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - ${DEPLOY_ROOT}/qbittorrent/config:/config
      - ${MEDIA_ROOT}:/video
    ports:
      - "7888:8080"  # 外部访问端口
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - nas-network  # 加入统一网络
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"