version: '3.8'
services:
  moviepilot:
    container_name: moviepilot-v2
    image: jxxghp/moviepilot-v2:2.1.5
    user: "1000:1000"
    networks:
      media_net:
        ipv4_address: 172.20.0.5
    volumes:
      - ':video'
      - '/moviepilot-v2/config:/config'
      - '/moviepilot-v2/playwright:/moviepilot/.cache/ms-playwright'
    environment:
      - TZ=Asia/Shanghai
      - UMASK=022
      - WEBUI_PORT=3005
    ports:
      - "3005:3005"
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  media_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
