services:
  transmission:
    image: linuxserver/transmission:4.0.5
    container_name: transmission
    ports:
      - 28005:9091
    volumes:
      - /transmission:/config
      - :/downloads
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/config/webui/Transmission Theme
      - USER=admin
      - PASS=password
    restart: always
    network_mode: bridge